### ISSUE TITLE
Homebridge v2.0.0 beta > homebridge-deconz

### ISSUE THREAD

**Issue by MSL-DA** [ebaauw/homebridge-deconz#223]
homebridge-deconz does not work with Homebridge version 2.0.0 beta11

```
[06/08/2024, 11:30:09] [deCONZ] warning: 192.168.30.10:4530: TypeError: this._accessory.getServiceByUUIDAndSubType is not a function
    at new ServiceDelegate (/var/lib/homebridge/node_modules/homebridge-deconz/node_modules/homebridge-lib/lib/ServiceDelegate/index.js:75:25)
    at new Button (/var/lib/homebridge/node_modules/homebridge-deconz/lib/DeconzService/Button.js:111:5)
    at new Gateway (/var/lib/homebridge/node_modules/homebridge-deconz/lib/DeconzAccessory/Gateway.js:239:26)
    at DeconzPlatform.foundGateway (/var/lib/homebridge/node_modules/homebridge-deconz/lib/DeconzPlatform.js:112:29)
    at DeconzPlatform.findHost (/var/lib/homebridge/node_modules/homebridge-deconz/lib/DeconzPlatform.js:122:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DeconzPlatform.init (/var/lib/homebridge/node_modules/homebridge-deconz/lib/DeconzPlatform.js:158:11) - retrying in 60s
```

**Comment by MSL-DA** [comment]
That's fine, I just wanted to point it out before v2 becomes official. No I do not (v1.8.4)

**Comment by ebaauw** [comment]
HAP-NodeJS v1.0 has removed `getServiceByUUIDAndSubType()` as breaking change, see https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0#hap-nodejs-v1.

**Comment by ebaauw** [comment]
Next version might take a while.  Still converting Homebridge deCONZ to use ECMAScript modules.  I'm now running my other (already updated) plugins against Homebridge v2.0.0-beta.11 and I'm not seeing any other issues.  Knock on wood.

**Comment by ebaauw** [comment]
In v1.0.13.
